# Data preparation for sentiment analysis

Importing packages

In [1]:
from scripts.constants import *

In [2]:
import numpy as np
import pandas as pd

In [3]:
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [4]:
from sklearn.model_selection import train_test_split

## 1. Extracting the data

Loading the dataset from the .csv file

In [5]:
df = pd.read_csv('../data/all_emotions_mini.csv', sep='|')
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,text,emotion
0,my anxiety is overwhelming,anxious
1,"the sun is shining, it's a beautiful day",happy
2,i wish i had taken a different path,regretful
3,the sadness of a lost friendship is heartbreaking,sad
4,i'm angry about the way people treat those who...,angry


Converting emotions to one-hot encoded numpy array

In [6]:
emotions = pd.get_dummies(df['emotion'])
emotions = np.array(emotions.values)
print(emotions, emotions.shape)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]] (7702, 14)


Converting texts into numpy array

In [7]:
texts = np.array(df['text'].values)
print(texts)

['my anxiety is overwhelming' "the sun is shining, it's a beautiful day"
 'i wish i had taken a different path' ...
 "i'm anxious about the future of the economy"
 'i feel like i could conquer the world'
 "i'm feeling a sense of dread as i prepare for my upcoming exam"]


## 2. Text vectorization

Creating a Tokenizer instance from Keras and fitting it on our corpus

In [8]:
tokenizer = Tokenizer(num_words=MAX_WORDS, filters=FILTERS, lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts(texts)
tokenizer.fit_on_texts(pd.read_csv('../data/all_emotions_mini.csv', sep='|')['text'].values)

Vectorizing text data

In [9]:
vectorized_texts = tokenizer.texts_to_sequences(texts)
vectorized_texts = pad_sequences(vectorized_texts, maxlen=MAX_TEXT_LEN)
print(vectorized_texts)

[[   0    0    0 ...   15  128   35]
 [   0    0    0 ...  232   18    4]
 [   0    0    0 ...  245  181   20]
 ...
 [   0    0    0 ...    1 1289    4]
 [   0    0    0 ...  551    1   94]
 [   0    0    0 ...   40   35   74]]


## 3. Preparing training and testing sets

Splitting the dataset into training (80%) and testing (20%) sets

In [10]:
x_train, x_test, y_train, y_test = train_test_split(vectorized_texts, emotions, test_size=0.2)

In [11]:
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(6161, 30) (1541, 30)
(6161, 14) (1541, 14)
